on: push
name: ðŸš€ Deploy website on push
jobs:
  laravel-tests:
    environment: Stagging
    name: ðŸŽ‰ Stag and Test
    runs-on: ubuntu-latest
    steps:
      - name: Select PHP Version
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.4'
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
      
  web-deploy:
    needs: [laravel-tests]
    environment: Production
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 2
      - name: ðŸ”¨ Create .env
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_APP_NAME: rekaapi
          ENV_APP_ENV: production
          ENV_APP_KEY: ''
          ENV_APP_DEBUG: false
          ENV_APP_URL: http://rekaabsensi.mojosemidinopark.com/
          ENV_DB_CONNECTION: mysql
          ENV_DB_HOST: 127.0.0.1
          ENV_DB_PORT: 3306
          ENV_DB_DATABASE: ${{ secrets.DB_NAME }}
          ENV_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          ENV_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ENV_SESSION_DOMAIN: ${{ secrets.HOST }}
          ENV_SANCTUM_STATEFUL_DOMAINS: ${{ secrets.HOST }}
      - name: ðŸ”¨ Generate .env key
        run: php artisan key:generate
      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          exclude: |
            */.git/*
            */.git/**
            .gitignore
            .gitattributes
            .env.example
            .env.testing
            DOCKER_ENV
